### ISSUE TITLE
Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by HBouch** [ozkanonur/vscode-deepdark-material#4]
When I try to set the color Theme, I get the error : "Cannot read property 'id' of undefined".

**Comment by ozkanonur** [comment]
Hey there, I'm sorry to hear that you got this error, but are you sure your vs code working properly? Because that issue doesn't look like extension's error. I will keep this issue as open until you tell me that you fixed the error and meanwhile I will also research the error if it's about the extension. Again sorry to hear that and please feedback me if you find anything about that error.

**Comment by HBouch** [comment]
You are right, I now get the error when trying to install any theme extension ...

**Comment by johhansantana** [comment]
@HBouch where you able to fix this? I'm getting this error when trying to install any theme from the marketplace
